<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>

    <?php echo $this->headTitle('prcms')->setAutoEscape(false) ?>

    <!-- Bootstrap core CSS -->
    <!-- Custom styles for this template -->
    <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/styles/admin/dashboard.css')
                    ->prependStylesheet($this->basePath() . '/styles/admin/bootstrap.min.css');?>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <?php echo $this->headscript()->appendFile($this->basepath() . '/scripts/admin/jquery.min.js')
               ->appendFile($this->basepath() . '/scripts/admin/ie-emulation-modes-warning.js')
               ->appendFile(
        	           $this->basepath() . '/scripts/admin/html5shiv.min.js',
                       'text/javascript',
                        array('conditional' => 'lt IE 9'))
               ->appendFile(
                        $this->basepath() . '/scripts/admin/respond.min.js',
                        'text/javascript',
                        array('conditional' => 'lt IE 9'));

    ?>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">PRCMS</a>
        </div>
        <div class="navbar-collapse collapse">
          <?php //echo $this->RenderAdminMenu();?>
          <?php echo $this->CurrentAdminUser();?>
        </div>

      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="main">
            <?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('partial/breadcrumbs');?>
            <?php echo $this->RenderAlert();?>
            <?php echo $this->content;?>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/scripts/admin/bootstrap.min.js"></script>
    <script src="/scripts/admin/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/scripts/admin/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>
