<?php
use Zend\Form\Element;
?>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">日志详情</h3>
  </div>
  <div class="panel-body">
  

<div id="searchContent"></div>

  		<?php 
            $log = $this->data;
  		?>
<fieldset>
		  <br/>
		  
		  <div class="form-group">
		    <div class="col-sm-10">
		   记录时间: <?php echo $log['date'];?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <div class="col-sm-10">
		    用户ID:<?php echo $log['user_id'];?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <div class="col-sm-10">
		    用户名:<?php echo $log['user_name'];?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <div class="col-sm-10">
		    访问ip:<?php echo $log['ip'];?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <div class="col-sm-10">
		    行为:<?php echo $log['title'];?>
		    </div>
		  </div>
		  <?php 
		      if($log['description']):
		      $description = json_decode($log['description']);
		      ?>
		  <div class="form-group">
		    <div class="col-sm-10">
		    详情:<?php 
		      foreach ($description as $key => $value):
		      echo "<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$this->escapehtml($key).":".$this->escapehtml($value);
		      endforeach;
		    
		    ?>
		    </div>
		  </div>				  
		  <?php 
		      endif;
		  ?>
</fieldset>		
</div>
</div>
