<?php
use Zend\Form\Element;
$form = $this->form;
?>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><?php echo $form->get('submit')->getValue()?></h3>
  </div>
  <div class="panel-body">
  		<?php 
  		$form->prepare();
  		echo $this->form()->openTag($form);
  		?>
  		
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">Module:</label>
		    <div class="col-sm-10">
		    	<?php
				    $name = $form->get('module_id');
				    echo $this->formSelect($name);
				     echo $this->formElementErrors($name,array('class'=>'alert alert-warning'));
				?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">名称:</label>
		    <div class="col-sm-10">
		    	<?php
				    $name = $form->get('name');
				    echo $this->formInput($name);
				     echo $this->formElementErrors($name,array('class'=>'alert alert-warning'));
				?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		  <label for="inputId" class="col-sm-2 control-label">描述:</label>
		  	<div class="col-sm-10">
		    	<?php
				    $name = $form->get('description');
				    echo $this->formTextarea($name);
				    echo $this->formElementErrors($name,array('class'=>'alert alert-warning'));
				?>
		    </div>
		  </div>
		  <div class="form-group">
		  <label for="inputId" class="col-sm-2 control-label"></label>
		  <div class="col-sm-10">
		  <?php echo $this->formElement($form->get('submit')) ?>&nbsp;<?php echo $this->formElement($form->get('cancel')) ?>
		  </div>
		  </div>		   	
		<?php echo $this->formElement($form->get('id')) ?>
		
		<?php echo $this->form()->closeTag() ?>
</div>
</div>