
<div class="panel panel-default">
 

  <div class="panel-body">
  <input type="text" maxlength="30" id="name"/><button id="addName">新增</button>
	<table id="obj_table" class="table table-striped">
			<tr>
				<th>项目名称</th>
				<th>操作</th>
			</tr> 
			 <?php foreach ($this->paginator as $row){ ?>
			<tr>
			    <td><?php echo $this->escapehtml($row['name']); ?></td>
			    <td>
			    	<?php if($row['id'] > 1):?>
			    		<a class="deleteProject" remove_id="<?php echo $row['id'];?>" style="cursor:pointer" href="">
			    		<?php 
			    			if($row['is_delete'] == 0):
			    				echo "隐藏";
			    			else:
			    				echo "取消隐藏";
			    			endif;
			    		?>
			    		</a>
			    	&nbsp;&nbsp;|&nbsp;&nbsp;
			    		<a class="removeName" remove_id="<?php echo $row['id'];?>" style="cursor:pointer" href="">删除</a>
			    	<?php endif;?>
			    </td>
			</tr>
			<?php } ?>
	</table>
	
</div>
</div>
<script>

$(document).on("click",'.removeName',function(e){
	var r = confirm("确定删除吗?");
	if(r == false){
		return false;
	}
	e.stopPropagation();
	var id = $(this).attr('remove_id');
	var trlink = $(this).parents("tr");
	$.ajax({
    	url: "/dictionary/delete-project",
    	type: "POST",
    	dataType: "json",
    	data: { id: id },
    	success: function(result) {
			if(result.code == 0){
				trlink.remove();
			}
			if(result.code == -1){
				alert('删除失败 关联工时记录已存在');
			}
			if(result.code == -2){
				alert('删除失败');
			}
    	}
	});
	return false;
});

$(document).on("click",'.deleteProject',function(e){
	e.stopPropagation();
	var id = $(this).attr('remove_id');
	var othis = $(this);
	$.ajax({
    	url: "/dictionary/disable-project",
    	type: "POST",
    	dataType: "json",
    	data: { id: id },
    	success: function(result) {
			if(result.code == 0){
				if(result.status == 1){
					othis.text('取消隐藏');
				}else{
					othis.text('隐藏');
				}
			}
    	}
	});
	return false;
});

(function($){
	$("#addName").click(function(e){
		var name = $.trim($("#name").val());
		if(name != ''){
			$(this).attr("disabled",true);
			$.ajax({
				url: "/dictionary/add-project",
				type: "POST",
				dataType: "json",
				data: { name: name },
				success: function(result) {
					var data = result.data;
					if(data.code == -2){
						alert('名称不能重复');
					}
					if(data.code == -1){
						alert('参数错误');
					}
					
					if(data.name != '' && data.id > 0){
						var rowTem = '<tr>'
			                + '<td>'+data.name+'</td>'
			                + '<td><a class="deleteProject" remove_id='+data.id+' style="cursor:pointer" href="">隐藏</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a class="removeName" style="cursor:pointer"  href="" remove_id='+data.id+'>删除</a></td>'
			                + '</tr>';
						$("#obj_table tbody:last").append(rowTem);
						$("#name").val('');
					}
					
				},
				complete: function() {
					$("#addName").attr("disabled",false);
				}
			});
		}
	});

})(jQuery);

</script>