<?php
use Zend\Form\Element;
?>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">FORGOT PASSWORD</h4>
  </div>
  <div class="panel-body">
<form action="/admin/auth/reset-password" class="form-signin"  role="form" method="POST">
<p class="form-signin-heading">If you are having trouble logging in please enter
	your email address below and we will send you your login credentials. </p>
	<div class="form-group">
<?php

$element = new Element\Email ( "email" );
$element->setAttributes(array(
	'class' => 'form-control'
));
echo $this->formemail ( $element );
?>
	</div>
	<div class="form-group">
<?php

$element = new Element\Submit ( "reminder" );
$element->setValue ( "Reset Password" );
$element->setAttribute ( "class", "btn btn-large" );
$element->setAttribute("class", "form-control");
echo $this->formsubmit ( $element );
?>
</div>
</form>
</div>
</div>
