<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">修改密码</h3>
  </div>
  <div class="panel-body">
  
<?php
	if($this->error){
?>
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<!-- 	<strong> Error </strong> The following errors have occurred:  -->
	<ul>
	<?php 
	  foreach ($this->error as $key=>$value):
	 ?>
	 	<?php if(is_array($value)): ?>
	 		<?php foreach ($value as $k=>$v): ?>
	 		<!--  <li> <?php echo $key.' '.$k.' : '.$v;  ?> </li>-->
	 		<li> <?php echo $v;  ?> </li>
	 		<?php endforeach; ?>
	 	<?php else: ?>
	 	<li><?php echo $value; ?> </li>
	 	<?php endif; ?>
	<?php
	  endforeach;
	 ?>
	 </ul>
</div>
<?php } ?>

<div id="searchContent"></div>

<fieldset>
<form action="/index/update-my-password" method="post" class="form-horizontal" id="password_form">		  
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">原密码:</label>
		    <div class="col-sm-10">
		    <input class="form-control" name="old_password" id="old_password" value="" required="required" type="password">
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">新密码(8-16位数字和字母):</label>
		    <div class="col-sm-10">
		    <input class="form-control" name="password" id="password" value="" required="required" type="password">
		    <span id="pwdWrong">密码格式错误</span>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">确认密码:</label>
		    <div class="col-sm-10">
		   	<input class="form-control" name="confirmation" id="confirmation" value="" required="required" type="password">
		    <span id="notSameSpan">两次密码不一致</span>
		    </div>
		  </div>
		  		  
		  <div class="form-group">
		  <label for="inputId" class="col-sm-2 control-label"></label>
		  <div class="col-sm-10">
		<input name="submit_password" id="submit_password" class="btn btn-primary btn-sm" value="修改密码" type="submit">
		  
		  </div>
		  </div>		
		  </form>   	
</fieldset>		

</div>
</div>


<script>
 (function($){
	$(function(){
		$("#notSameSpan").hide();
		$("#pwdWrong").hide();
		$("#password_form").submit(function(e){
			var patrn=/^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{8,16}$/;
			var newPassword = $.trim($("#password").val());
	        if (patrn.test(newPassword)) {
	        	$("#pwdWrong").hide();
	        } else {
	        	$("#pwdWrong").show();
	        	return false;
	        }
			
			var newConfirmPassword = $.trim($("#confirmation").val());
			if(newPassword != "" && newConfirmPassword != ""){
				if(newPassword != newConfirmPassword){
					$("#notSameSpan").show();
					return false;
				}
			}
		});
	});
	
})(jQuery);
</script>